model:
  model_name: mixtral
system:
  gpu_gen: A100
  nvlink_gen: 3
  infiniband_gen: 800
  num_node: 1
  num_device: 1
  processor_type: GPU
  distribution:
    none_expert_tensor_degree: 1
    expert_tensor_degree: 1
  optimization:
    parallel_execution: 'off'
    hetero_subbatch: false
    disagg_system: false
    use_low_unit_moe_only: false
    use_ramulator: 'on'
    offchip_dram_cfg_path: reproduction_A100/with_off_chip_dram/configs/dram_config_DDR5.yaml
    compressed_kv: true
    use_absorb: true
    use_flash_mla: true
    use_flash_attention: true
    reuse_kv_cache: true
    kv_cache_reuse_rate: 0.0
    prefill_mode: false
    decode_mode: true
serving:
  max_batch_size: 1
  max_process_token: 0
simulation:
  data: synthesis
  input_len: 32
  output_len: 2
  precision_byte: 2
  skewness: 0.0
  iter: 2
  injection_rate: 0
  exit_out_of_memory: false
  mem_cap_limit: false
log:
  print_log: true
  export_gantt: true
  output_directory: reproduction_A100/with_off_chip_dram/results/b0_offchip_dram/csv/
  gantt_directory: reproduction_A100/with_off_chip_dram/results/b0_offchip_dram/raw/
